- fixed support for CNFS in put.news.sm
Changed files:
    suck-PLD.patch -> 1.3

diff --git a/suck-PLD.patch b/suck-PLD.patch
--- a/suck-PLD.patch
+++ b/suck-PLD.patch
@@ -1,5 +1,6 @@
+diff -ruN suck-4.2.2.orig/Makefile.in suck-4.2.2/Makefile.in
 --- suck-4.2.2.orig/Makefile.in	Sun Jul 25 21:09:33 1999
-+++ suck-4.2.2/Makefile.in	Tue Nov  2 10:19:14 1999
++++ suck-4.2.2/Makefile.in	Mon Dec  6 08:21:47 1999
 @@ -6,8 +6,8 @@
  ############################################################################
  
@@ -66,8 +67,9 @@
  CPPFLAGS = -I. -I$(srcdir) @CPPFLAGS@
  LDFLAGS = @LDFLAGS@ 
  DEFS = @DEFS@ -DSUCK_VERSION=\"$(VERSION)\"
+diff -ruN suck-4.2.2.orig/README.FIRST suck-4.2.2/README.FIRST
 --- suck-4.2.2.orig/README.FIRST	Thu Jan  1 01:00:00 1970
-+++ suck-4.2.2/README.FIRST	Tue Nov  2 10:16:33 1999
++++ suck-4.2.2/README.FIRST	Mon Dec  6 08:21:47 1999
 @@ -0,0 +1,25 @@
 +Dear user,
 +
@@ -94,8 +96,9 @@
 +Bye,
 +    Karsten Weiss <karsten@addx.au.s.shuttle.de>
 +
+diff -ruN suck-4.2.2.orig/killprg.c suck-4.2.2/killprg.c
 --- suck-4.2.2.orig/killprg.c	Tue May 11 16:36:36 1999
-+++ suck-4.2.2/killprg.c	Tue Nov  2 10:16:01 1999
++++ suck-4.2.2/killprg.c	Mon Dec  6 08:21:47 1999
 @@ -395,9 +395,12 @@
  }
  /*--------------------------------------------------------------------------*/
@@ -112,8 +115,9 @@
  	master->killfunc=chk_msg_kill; /* restore default function */
  }
  /*----------------------------------------------------------------------------*/
+diff -ruN suck-4.2.2.orig/sample/get.news.generic suck-4.2.2/sample/get.news.generic
 --- suck-4.2.2.orig/sample/get.news.generic	Sat Feb 20 00:32:57 1999
-+++ suck-4.2.2/sample/get.news.generic	Tue Nov  2 10:24:44 1999
++++ suck-4.2.2/sample/get.news.generic	Mon Dec  6 08:21:47 1999
 @@ -5,20 +5,19 @@
  #NOTE: this script probably needs to be run by root.  Most systems will
  # not let a normal user run rnews
@@ -140,8 +144,9 @@
  SCRIPT=${BASEDIR}/put.news		# my filter for rpost
  OUTFILE=/tmp/tmp$$			# used by rpost as article after it is filtered
  LOCKFILE=${BASEDIR}/getnews.lock	# lock file to prevent multiple instances of script
+diff -ruN suck-4.2.2.orig/sample/get.news.inn suck-4.2.2/sample/get.news.inn
 --- suck-4.2.2.orig/sample/get.news.inn	Sat Sep 27 09:29:59 1997
-+++ suck-4.2.2/sample/get.news.inn	Tue Nov  2 10:24:39 1999
++++ suck-4.2.2/sample/get.news.inn	Mon Dec  6 08:21:47 1999
 @@ -5,12 +5,13 @@
  #NOTE: this script probably needs to be run by root.  Most systems will
  # not let a normal user run ctlinnd 
@@ -312,8 +317,9 @@
  	echo "You can hang up the modem now"
  
  fi
+diff -ruN suck-4.2.2.orig/sample/put.news suck-4.2.2/sample/put.news
 --- suck-4.2.2.orig/sample/put.news	Sun Oct  4 21:32:26 1998
-+++ suck-4.2.2/sample/put.news	Tue Nov  2 10:16:26 1999
++++ suck-4.2.2/sample/put.news	Mon Dec  6 08:21:47 1999
 @@ -1,34 +1,10 @@
  #!/bin/sh
  
@@ -357,8 +363,36 @@
 +	/^$/ {body = 1}
 +	body || !/^(NNTP-Posting-Host|Xref):/
 +' $1 >$2
+diff -ruN suck-4.2.2.orig/sample/put.news.sm suck-4.2.2/sample/put.news.sm
+--- suck-4.2.2.orig/sample/put.news.sm	Tue Dec  1 02:05:52 1998
++++ suck-4.2.2/sample/put.news.sm	Mon Dec  6 08:23:51 1999
+@@ -6,19 +6,7 @@
+ # It is set up for INND using CNFS, so it uses the sm command
+ # to get the actual article
+ 
+-TMPFILE=/tmp/tmp$$
+-SEDCMD="/^NNTP-Posting-Host/d"
+-SEDCMD2="/^Xref/d"
+-OUTFILE=$2
+-
+-/usr/news/bin/sm $1 > $TMPFILE
+-
+-if [ -f ${TMPFILE} ]; then
+-
+-	sed -e ${SEDCMD} ${TMPFILE} | sed -e ${SEDCMD2} > ${OUTFILE}
+-		
+-	if [ $? -ne 0 ]; then
+-		echo "Error"
+-		exit -1
+-	fi
+-fi
++/usr/bin/sm $1 | awk '
++    /^$/ {body = 1}
++    body || !/^(NNTP-Posting-Host|NNTP-Posting-Date|X-Trace|X-Complaints-To|Xref):/
++    ' > $2
+diff -ruN suck-4.2.2.orig/suck_config.h suck-4.2.2/suck_config.h
 --- suck-4.2.2.orig/suck_config.h	Sat May 15 23:26:59 1999
-+++ suck-4.2.2/suck_config.h	Tue Nov  2 10:15:28 1999
++++ suck-4.2.2/suck_config.h	Mon Dec  6 08:21:47 1999
 @@ -66,7 +66,7 @@
  
  /* FULL PATH of error log used if -e option specifed to any of the programs */
